name: BrickBoard
main: io.github.bananapuncher714.brickboard.BrickBoard
version: 0.7
description: GUIS made easy with chat
author: BananaPuncher714

softdepend:
- "MVdWPlaceholderAPI"
- "PlaceholderAPI"

commands:
  brickboard:
    aliases:
    - "bb"