name: BrickBoard
main: io.github.bananapuncher714.brickboard.BrickBoard
version: 0.2
description: GUIS made easy with chat
author: BananaPuncher714
commands:
  len:
    description: Test command
  brickboard:
    description: Does stuff